model: moonshotai/Kimi-K2.5
gpu-memory-utilization: 0.95
max-model-len: 8192
trust-remote-code: true
mm-encoder-tp-mode: data
tool-call-parser: kimi_k2
reasoning-parser: kimi_k2
speculative-config: '{"model":"lightseekorg/kimi-k2.5-eagle3-mla","method":"eagle3","num_speculative_tokens":3}'
